# Generated by Django 4.2.4 on 2023-08-29 17:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('destinstion', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=100)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detail_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(max_length=254)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id_type', models.CharField(max_length=100)),
                ('national_id', models.CharField(choices=[('Aadhar Number', 'Aadhar Number'), ('Civil Id', 'Civil Id'), ('PAN card', 'PAN card')], max_length=100)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Profile_image')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detail_management.customer')),
            ],
        ),
    ]
