# Generated by Django 4.2.4 on 2023-08-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_management.customer'),
        ),
    ]
