# Generated by Django 4.2.4 on 2023-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_management', '0002_alter_travelhistory_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='national_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='national_id_type',
            field=models.CharField(choices=[('Aadhar Number', 'Aadhar Number'), ('Civil Id', 'Civil Id'), ('PAN card', 'PAN card')], max_length=100),
        ),
    ]
