# Generated by Django 4.2.4 on 2023-08-29 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detail_management', '0003_alter_customerprofile_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
